<h2 class="nodisplay">Conrol Panel</h2>
<ul>
<li><a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'generalsettings'), 
                             null, 
                             true ); 
             ?>" 
             id="general-icon" class="icon"></a>
   
    <a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'generalsettings'), 
                             null, 
                             true ); 
             ?>">General Settings</a></li>

<li><a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'usersgroups'), 
                             null, 
                             true ); 
             ?>" 
             id="users-groups-icon" class="icon"></a>
   
    <a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'usersgroups'), 
                             null, 
                             true ); 
             ?>">Users &#38; groups</a></li>

<li><a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'ports'), 
                             null, 
                             true ); 
             ?>" 
             id="ports-manager-icon" class="icon"></a>

    <a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'ports'), 
                             null, 
                             true ); 
             ?>">Ports Manager</a></li>

<li><a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'cache'), 
                             null, 
                             true ); 
             ?>"
             id="cache-icon" class="icon"></a>

    <a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'cache'), 
                             null, 
                             true ); 
             ?>">Cache Manager</a></li>

<li><a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'monitor'), 
                             null, 
                             true ); 
             ?>" 
             id="monitor-icon" class="icon"></a>

    <a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'monitor'), 
                             null, 
                             true ); 
             ?>">Traffic Monitor</a></li>

<li><a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'log'), 
                             null, 
                             true ); 
             ?>" 
             id="log-icon" class="icon"></a>

    <a href="<?php 
             echo $this->url(array('controller' => 'Gateway',
                                   'action' => 'log'), 
                             null, 
                             true ); 
             ?>">Logging Manager</a></li>
</ul>
