<h2 class="nodisplay">Conrol Panel</h2>
<ul>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'new-admin' ),
                              null,
                              true );
             ?>" 
             id="new-admin-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'new-admin' ),
                              null,
                              true );
             ?>">New Admin</a></li>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'new-admin-group' ),
                              null,
                              true );
             ?>" 
             id="new-admin-group-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'new-admin-group' ),
                              null,
                              true );
             ?>">New Admin Group</a></li>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'search-admins' ),
                              null,
                              true );
             ?>" 
             id="search-admins-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'search-admins' ),
                              null,
                              true );
             ?>">Search Admins</a></li>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'search-admin-groups' ),
                              null,
                              true );
             ?>" 
             id="search-admin-groups-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'search-admin-groups' ),
                              null,
                              true );
             ?>">Search Admin Groups</a></li>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'import-admins' ),
                              null,
                              true );
             ?>" 
             id="import-admins-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'import-admins' ),
                              null,
                              true );
             ?>">Import Admins</a></li>

</ul>

