<h2 class="nodisplay">Conrol Panel</h2>
<ul>
<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'admins-and-groups' ),
                              null,
                              true );
             ?>" 
             id="admins-and-groups-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'admins-and-groups' ),
                              null,
                              true );
             ?>">Admins &#38; Groups</a></li>
</ul>
