<h2 class="nodisplay">Conrol Panel</h2>
<ul>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'newmanager' ),
                              null,
                              true );
             ?>" 
             id="new-manager-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'newmanager' ),
                              null,
                              true );
             ?>">New Manager</a></li>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'newgroup' ),
                              null,
                              true );
             ?>" 
             id="new-group-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'newgroup' ),
                              null,
                              true );
             ?>">New Managers Group</a></li>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'searchmanagers' ),
                              null,
                              true );
             ?>" 
             id="search-managers-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'searchmanagers' ),
                              null,
                              true );
             ?>">Search Managers</a></li>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'searchgroups' ),
                              null,
                              true );
             ?>" 
             id="search-manager-groups-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'searchgroups' ),
                              null,
                              true );
             ?>">Search Manager Groups</a></li>

<li><a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'importmanager' ),
                              null,
                              true );
             ?>" 
             id="import-manager-icon" class="icon"></a>

    <a href="<?php
             echo $this->url( array( 'controller' => 'Administration',
                                     'action' => 'importmanager' ),
                              null,
                              true );
             ?>">Import Manager</a></li>

</ul>

